### ISSUE TITLE
[1.14.3] The RF extractor doesn't drop when broken.

### ISSUE THREAD

**Issue by ProsperCraft** [DoctorFTB/Bio-Technik#1]
When you break an RF extractor it doesn't have hardness, breaks instantly and does not give it as a a drop.

BioTechnik-1.14.3-1.0.0
forge-1.14.3-27.0.25

Modpack - https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by DoctorFTB** [comment]
Try 1.0.1 version.
Fixed.

**Comment by ProsperCraft** [comment]
Resolved
