### ISSUE TITLE
[1.14.3] Feature request - keep power when broken.

### ISSUE THREAD

**Issue by ProsperCraft** [DoctorFTB/Bio-Technik#2]
As this block is a battery of sorts, perhaps it could keep its rf when broken and placed?

**Comment by DoctorFTB** [comment]
Block was not planned like battery, 1.000.000 energy, it is small storage.
I think I can change from 1.000.000, to 100.000, but I don't think it is necessary..

**Comment by ProsperCraft** [comment]
We have batteries in the pack now so not as important, thank you.
